In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

## **Part 1- Data Preprocessing**

### Importing Dataset

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/datasets/Churn_Modelling.csv")
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [ ]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

## Encoding Categorical Data

label encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
print(x)
print(x[0])

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[619 'France' 0 42 2 0.0 1 1 1 101348.88]


One Hot Encoding the **Geography** Column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)
print(x[0])

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


## Splitting the data into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

## `Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

# **Part 2 - Building the ANN**

Intializing the ANN

In [ ]:
ann = tf.keras.Sequential()

Adding the input layer and first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=200,activation="relu"))

Adding the Second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=200,activation="relu"))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# **Part 3 - Training the ANN**

Compiling the ANN

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

Training the ANN on Training Set

In [ ]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8251
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8556
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3420 - accuracy: 0.8597
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8624
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3305 - accuracy: 0.8636
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3264 - accuracy: 0.8658
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3226 - accuracy: 0.8686
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3186 - accuracy: 0.8709
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3177 - accuracy: 0.8696
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3134 - accura

# **Part 4 - Making predictions and evaluating the model**

In [ ]:
print(ann.predict(sc.transform([[0, 0, 1, 608, 1, 41, 1, 83807, 1 , 0, 1,112542.88]]))> 0.5)

[[False]]


In [ ]:
Y_pred=ann.predict(X_test)
Y_pred=(Y_pred>0.5)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,Y_pred))

[[1397  198]
 [ 178  227]]


In [ ]:
accuracy_score(Y_test,Y_pred)

0.812